#![allow(unused)]

crate::open_enum! {
    pub enum Class: i32 {
        Barbarian = 0,
        Bard = 1,
        Cleric = 2,
        Druid = 3,
        Fighter = 4,
        Monk = 5,
        Paladin = 6,
        Ranger = 7,
        Rogue = 8,
        Sorcerer = 9,
        Wizard = 10,
        Aberration = 11,
        Animal = 12,
        Construct = 13,
        Humanoid = 14,
        Monstrous = 15,
        Elemental = 16,
        Fey = 17,
        Dragon = 18,
        Undead = 19,
        Commoner = 20,
        Beast = 21,
        Giant = 22,
        MagicBeast = 23,
        Outsider = 24,
        Shapechanger = 25,
        Vermin = 26,
        Shadowdancer = 27,
        Harper = 28,
        ArcaneArcher = 29,
        Assassin = 30,
        Blackguard = 31,
        DivineChampion = 32,
        WeaponMaster = 33,
        PaleMaster = 34,
        ShifterCUT = 35,
        DwarvenDefender = 36,
        DragonDisciple = 37,
        Ooze = 38,
        Warlock = 39,
        ArcaneTrickster = 40,
        CavalierCUT = 41,
        ContemplativeCUT = 42,
        FrenziedBerserker = 43,
        MysticTheurgeCUT = 44,
        SacredFistCUT = 45,
        ShadowThiefofAmn = 46,
        NWNineWarder = 47,
        Duelist = 50,
        Warpriest = 51,
        EldritchKnight = 52,
    }
}
